### ISSUE TITLE
`make` doesn't work

### ISSUE THREAD

**Issue by r-barnes** [cfmmoc/cfmmoc#2]
This is Richard Barnes, Associate Editor of Computers & Geosciences.

Running Make in the obj directory leads to the following error:

    cp ../bin/libRQTS.so .
    cp: cannot stat '../bin/libRQTS.so': No such file or directory
    Makefile:32: recipe for target 'b.so' failed

It looks as though the make process expects a pre-compiled `libRQTS.so` in the `bin/` directory. Your code **must not** rely on pre-compiled libraries included with the source, as these are not likely to be portable across systems. Rather, your makefile should include directives for compiling the needed libraries or your `README` should clearly describe how to acquire said libraries.

If you believe a library may cease to be available in the future, including its source with your project is permissible.

Please resolve the foregoing.

**Comment by cfmmoc** [comment]
We have made libRQTS as an open source library (https://github.com/cfmmoc/libRQTS).
In addition, a compiled version of libRQTS was added to bin/ directory. Hence, make command works.
We also made the source of executable file cfMMOC public (in browser/ directory).
