### ISSUE TITLE
`Makefile` in non-standard location.

### ISSUE THREAD

**Issue by r-barnes** [cfmmoc/cfmmoc#3]
This is Richard Barnes, Associate Editor of Computers & Geosciences.

Including the `makefile` inside the `obj/` directory is highly non-standard. It is more usual to have the makefile outside the `obj/` directory and to run, e.g.,

    mkdir obj
    cd obj
    make -f ../Makefile

Please read up on the appropriate use of makefiles or exam other projects and modify accordingly.

**Comment by cfmmoc** [comment]
We moved makefile from obj/ directory to root directory and added building directives in README file.
