### ISSUE TITLE
Code Commenting

### ISSUE THREAD

**Issue by r-barnes** [cfmmoc/cfmmoc#4]
This is Richard Barnes, Associate Editor of Computers & Geosciences.

I've noticed that your source code has almost no comments.

This makes it difficult for other researchers to use or modify your code.

Please add sufficient comments for outside users unfamiliar with your code to discover the purpose of its various parts and understand the rationale behind the various decisions made in the code.

This is roughly the level of commenting I expect to see with code: https://github.com/r-barnes/BarnesClark2017-Salamanders/blob/master/src/phylo.cpp

**Comment by r-barnes** [comment]
[This code](https://github.com/r-barnes/richdem/blob/master/include/richdem/depressions/Barnes2014.hpp) provides a better example of how to comment functions/methods.

**Comment by cfmmoc** [comment]
Thanks for the comments and guiding references. We have added comments regarding member functions and key parts of code for all sources and headers.
